//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_EMR_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habit
    {
        public long Patient_Id { get; set; }
        public long Habit_Id { get; set; }
        public string Habit_Name { get; set; }
    
        public virtual General_Examination General_Examination { get; set; }
    }
}
