//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_EMR_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long Patient_Id { get; set; }
        public long Doctor_Id { get; set; }
        public long Organization_Id { get; set; }
        public System.DateTime rev_date { get; set; }
        public string rev_midicine { get; set; }
        public string rev_description_result { get; set; }
        public long review_Id { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Medical_Organization Medical_Organization { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
