//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GP_EMR_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long User_Id { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Last_Date_Of_Login { get; set; }
        public int User_Type { get; set; }
        public string Password { get; set; }
        public int Status_Of_Account { get; set; }
        public string City { get; set; }
        public string Photo_Url { get; set; }
    
        public virtual Medical_Organization Medical_Organization { get; set; }
        public virtual Person Person { get; set; }
    }
}
